[script]
name = "wr_official"
version = "0.1.0"
author_ids = ["yourName"]
description = "yourDescription"
repository = "https://anyTextButShouldBeLinkToYourRepository"
tags = ["official", "wr"]

[dependencies]
partitions = "0.1.0"